name: DEPLOY - PROD
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.3.0
        with:
          # Contexto onde está o arquivo Dockerfile, normalmente é .
          context: .
          file: Dockerfile.prod
          # Qual a tag
          tags: gabrielsoaresdev/lumen-test:latest
          no-cache: true
          push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update image in stack
        uses: distributhor/workflow-webhook@v2
        env:
         webhook_url: ${{secrets.TOKEN_ACTION_GIT}}
         webhook_secret: "Y0uR5ecr3t"
         verify_ssl: false
